import 'package:get/get.dart';

class Mytranlaztion extends Translations{
  @override
  Map<String, Map<String, String>> get keys =>{
    "ar":{
      "1":"ابحث عن حجزك",
      "2":"نساعدك علئ البحث ضمن مواعيد حجز عدد كبير من شركات النقل بضغطه زر",
      "3":"الحجز او لاين",
      "4":"نساعدك علئ حجز رحلات بشكل اسرع دون تكبد عناء الذهاب الئ محطات النقل",
      "5":"الحجز او لاين",
      "6":"نساعدك علئ حجز رحلات بشكل اسرع دون تكبد عناء الذهاب الئ محطات النقل",
      "7":" تسجيل الدخول",
      "8":"الجوال",
      "9":"البريد الإلكتروني",
      "10":"كلمة المرور",
      "11":"هل نسيت كلمة المرور؟",
      "12":"دخول",
      "13":"الدخول كزائر",
      "14":"ليس لديك حساب؟",
      "15":"أنشئ حسابا",
      "16":"الرجاء إدخال البريد الإلكتروني",
      "17":"صيغة البريد الإلكتروني غير صحيحة",
      "18":"الرجاء إدخال كلمة المرور",
      "19":"الرجاء إدخال رقم الهاتف",
      "20":"فشل تسجيل الدخول",
      "21":"بيانات الاعتماد غير صحيحة. الرجاء المحاولة مرة أخرى.",
      "22":"يجب ادخال اسم المستخدم",
      "23":"رقم الجوال مطلوب",
      "24":"البريد الإلكتروني مطلوب",
      "25":"كلمة المرور لا تقل عن 6 أحرفب",
      "26":"كلمتا المرور غير متطابقتين",
      "27":"ذكر",
      "28":"أنثئ",
      "29":"إنشاء حساب",
      "30":"الاسم الكامل",
      "31":"الجنس",
      "32":"تأكيد كلمة المرور",
      "33":"نسيت كلمه المرور",
      "34":"أدخل بريدك الالكتروني المسجل أدناه لتلقي",
      "35":"تعليمات إعاده تعيين كلمه المرور",
      "36":" إنشاء كلمه المرور الجديده",
      "37":"يجب أن تكون كلمه المرور الجديده الخاصه بك مختلفه عن كلمه المرور المستخدمه سابقا ",
      "38":"موافق",
      "39":"ارسال",
      "40":"الرئيسية",
      "41":"حجوزاتي",
      "42":"المسافرين",
      "43":"الإعدادات",
      "44":"الأشعارات",
      "45":"الكل",
      "46":"الحجوزات",
      "47":"العروض",
      "48":"التحديثات",
      "49":"رقم الجوال ",
      "50":"البحث ",
      "51":"التحقق من الايميل ",



    },
    "en":{
      "1":"Find your reservation",
      "2":"We help you search within the times of booking a large number of \n transportation companies with the click of abutton",
      "3":"Book online",
      "4":"We help you to book flights faster,without the trouble\n of going to the transporation stations",
      "5":"Book online",
      "6":"We help you to book flights faster,without the trouble\n of going to the transporation stations",
      "7":"Login",
      "8":"Phone ",
      "9":"Email",
      "10":"Password",
      "11":"Did you forget the password?",
      "12":"Login",
      "13":"Entry as visitor",
      "14":"You don`t have an account?",
      "15":"Create an account",
      "16":"Please enter the email",
      "17":"The e-mail format is correct",
      "18":"Please enter your password",
      "19":"Please enter your phone",
      "20":"Login Failed",
      "21":"The credentials are incorrect,please try again",
      "22":"You must enter the username",
      "23":"The phone number is required ",
      "24":"Email is required",
      "25":"The password is not less than 6 letters",
      "26":"The tow password are not identical",
      "27":"Mael",
      "28":"Female",
      "29":"Create an account",
      "30":"Fual name",
      "31":"Sex",
      "32":"Confirm the password",
      "33":"Forget your password",
      "34":"Enter your registered email below to receive",
      "35":"password reset instuction",
      "36":"Creat new password",
      "37":"Your new password must be differenet from \n previously used passwords",
      "38":"Ok",
      "39":"Send",
      "40":"Home",
      "41":"Reservation",
      "42":"Travlers",
      "43":"Setting",
      "44":"Notifications",
      "45":"All",
      "46":"Reservation",
      "47":"Offers",
      "48":"Updates",
      "49":"Phone number",
      "50":"Sherch",
      "51":"Check of E-mail",

    }
  };

}